project:
  type: website

website:
  title: "proquant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: presentations.qmd
        text: Presentations
      - href: literature.qmd
        text: Literature
      

format:
  html:
    theme: yeti
    css: styles.css




