project:
  type: website
  output-dir: _site
  

website:
  sidebar:
    style: "docked"
    logo: assets/proquant.png
    contents:
      - href: index.qmd
        text: Home
      - href: gleason4.qmd
        text: What is wrong with the Gleason score?
      - href: pathogist.qmd
        text: Why is there variation between pathologists measurements?
      - href: literature.qmd
        text: Peer-Reviewed Literature
  favicon: assets/proquant.png
  search: false
      

format:
  html:
    theme: cosmo
    css: styles.css

metadata:
  pagetitle: "proquant"
   




