project:
  type: website
  

website:
  favicon: assets/proquant.png
  search: false
  navbar:
    logo: assets/proquant.png
    left:
      - href: index.qmd
        text: Home
      - href: presentations.qmd
        text: Presentations
      - href: literature.qmd
        text: Peer-Reviewed Literature
      

format:
  html:
    theme: cosmo
    css: styles.css

metadata:
  pagetitle: "proquant"
   




