name: Quarto Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libc6-dev \
          build-essential \
          libpng-dev \
          libgdal-dev \
          gdal-bin \
          libproj-dev \
          libgeos-dev \
          libudunits2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libtiff-dev \
          libjpeg-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libglpk-dev \
          libsqlite3-dev \
          libmagick++-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/renv
            ~/Library/Caches/renv
            ~/.cache/renv
            ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            ${{ runner.os }}-

      - name: Install R dependencies
        run: |
          install.packages("renv", repos = "https://cloud.r-project.org")
          # Set up parallel installation
          options(Ncpus = 2)
          # Check if packages are already installed
          if (renv::status()$synchronized) {
            cat("All packages are already synchronized, skipping restore\n")
          } else {
            cat("Restoring packages from lockfile\n")
            renv::restore(confirm = FALSE, library = .libPaths()[1])
          }
        shell: Rscript {0}

      - name: Show R library paths
        run: Rscript -e '.libPaths()'

      - name: Render Quarto Project
        run: quarto render

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
